version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
    # environment:
    #   - WATCHFILES_FORCE_POLLING=true  # 環境によってホットリロードのために必要
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.conf:/etc/mysql/conf.d/my.conf
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
volumes:
  mysql_data: