name: pytest-github-actions
run-name: ${ github.actor } is running pytest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest
